export const projects = [
  {
    title: 'Website with Fetch API',
    description: "You are to provide the ingridients and the website will generate all the delicious meals along with their recipes. The recipe is both in a script-format as well as there is video link to the recipe.",
      image: '/images/1.png',
      tags: ['HTML', 'CSS', 'Javascript', 'Fetch-Api'],
    source: 'https://github.com/Sreejavastar/Website-with-Fetch-API-',
    visit: 'https://lovenlemons.netlify.app/',
    id: 0,
  },
  {
    title: 'E-Commerce Coffee Website',
    description:" A visually appealing website for buying coffee of your choice. You can buy coffee of your choice as well learn about the past buyers and contributors to this site.- FrontEnd Deployment",
    image: '/images/2.png',
    tags: ['HTML', 'CSS', 'Javascript'],
    source: 'https://github.com/Sreejavastar/Coffee-website',
    visit: 'https://coffeeco.netlify.app/#blogs',
    id: 1,
  },
  {
    title: 'A Game Web Application',
    description: "This gamming web application aims at spreading precationary steps that one should take as well as the rules one should follow during the outbreak of COVID-19 and all of this can be done while entertaining you with an addictive game and a beautiful UI.",
      image: '/images/3.png',
      tags: ['HTML', 'CSS', 'Javascript'],
    source: 'https://github.com/Sreejavastar/Covi-Covi',
    visit: 'https://poetic-kitsune-7f85c4.netlify.app/',
    id: 2,
  },
  {
    title: 'Todo List',
    description: "A React based web application with a powerful and user-friendly UI that will help you make your own TO-DO list, however with some special added features that has enhanced its accessibility.",
    image: '/images/4.png',
    tags: ['React', 'CSS', 'JavaScript'],
    source: 'https://github.com/Sreejavastar/To-Do-List-with-React',
    visit: 'https://todoto-io.netlify.app/',
    id: 3,
  },
  {
    title: 'Animated CSS Website',
    description: "This is an Animated website where I have tried to deploy animation via CSS. Here we scroll down the website and we can see a beautiful dynamic page unfold",
    image: '/images/5.png',
    tags: ['HTML', 'CSS'],
    source: 'https://github.com/Sreejavastar/Save-Nature-with-beautiful-AI-and-parallax-scrrollig',
    visit: 'https://savenature-animated.netlify.app/#',
    id: 4,
  },
  {
    title: 'A Music Web Application',
    description: "This is a Web Application, where we can play music. It has been designed beautifully with amazing animations and gives you a real music player like feel",
    image: '/images/6.png',
    tags: ['HTML', 'CSS', 'JavaScript'],
    source: 'https://github.com/Sreejavastar/A-Real-Music-Application',
    visit: 'https://music-and-mp3.netlify.app/',
    id: 5,
  },
  {
    title: 'Web App using Firebase',
    description: " Shopper's List App is built to help daily shopping addicts to jot down all the essentials. It has very cute and aesthetic UI.",
    image: '/images/7.png',
    tags: ['React', 'Firebase'],
    source: 'https://github.com/Sreejavastar/Shopper-s-List-with-Firebase',
    visit: 'https://shopperslist.netlify.app/',
    id: 6,
  },
  {
    title: 'Face Emotion Detection',
    description: "In this project there is up a real time face detection through a webcam using AI. This AI is so quick that we are able to draw in real time the various faces and expressions of every person in the video without much performance overhead. We will be using the Face API JS library built on Tensor Flow to setup the face detection.",
    image: '/images/8.png',
    tags: ['JavaScript', 'face API', 'AI'],
    source: 'https://github.com/Sreejavastar/Face-Detection-Using-Javascript',
    visit: 'https://github.com/Sreejavastar/Face-Detection-Using-Javascript',
    id: 7,
  },
];

export const TimeLineData = [
  { year: 'HTML', text: '', },
  { year: 'CSS', text: '', },
  { year: 'ES6', text: '', },
  { year: 'JavaScript', text: '', },
  { year: 'React', text: '', },
  { year: 'Nextjs', text: '', },
  { year: 'Figma', text: '', },
  { year: 'Java', text: '', },
  { year: 'MySQL', text: '', },
];